### ISSUE TITLE
Description gets duplicated when editing

### ISSUE THREAD

**Issue by githubmin** [squallstar/fragments#22]
wrong description

**Comment by squallstar** [comment]
What?

**Comment by githubmin** [comment]
Try save fragment's description with 'aaa', it shows 'aaaaaa' after edit

**Comment by squallstar** [comment]
So you're saying the description gets duplicated. I couldn't really understand what you meant by reading "edit description" and "wrong description"...

- Does it happen every time?
- How can I replicate it easily?

**Comment by githubmin** [comment]
1. Type 'hello' to save a note fragment.
2. Right click the fragment, and select Edit.
3. change the empty description to 'aaa' and save it, then appears 'aaaaaa'
